config/routes.rb
Rails.application.routes.draw do
  root 'flights#home'
  get '/search', to: 'flights#search'
  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arrivals, class_name: "Flight", foreign_key: "from_airport"
  has_many :departures, class_name: "Flight", foreign_key: "to_airport"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers 
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport, class_name: "Airport"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_one :flight, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @totalPrice = @flight.price * params[:passengers].to_i
    @booking = Booking.new
    params[:passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(passenger_params)
    if @booking.save
      redirect_to booking_path(@booking.id)
    else 
      redirect_to new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers.all
    @totalPrice = @flight.price * @passengers.length
  end

  private

    def passenger_params
      params.require(:booking).permit(:flight_id, 
        passengers_attributes: [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def home 
    @airports = Airport.all.map{ |a| [ a.location, a.id] }
  end

  def search
    if params[:to] === params[:from]
      flash[:danger] = "Please enter two different airports."
      redirect_to root_url
    else
      @totalFlights = Flight.where(from_airport: params[:from], 
        to_airport_id: params[:to])
      @flights = Flight.where(from_airport: params[:from], 
        to_airport_id: params[:to]).order(params[:option] || :date).paginate(:page => params[:page], :per_page => 10)
      @params = {
        to: params[:to],
        from: params[:from],
        passengers: params[:passengers],
        option: params[:option]
      }
    end
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def priceAdjuster(flight, params)
    flight.price * params[:passengers].to_i
  end

  def endTime(flight)
    (flight.date + flight.duration.to_i * 60 * 60).strftime("%H:%M")
  end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/_flight.html.erb
<div class="flight-details">
  <header class="details-header">
    <h6>Flight ID: <%= @flight.id%></h6>
    <h6> (<%= @flight.from_airport.airport_code %>
      <i class="fas fa-arrow-right"></i> 
      <%= @flight.to_airport.airport_code %>)
    </h6>
  </header>
  <main class="details-main">
    <div class="flight-card-detail"> 
      <p><%= @flight.date.strftime("%d/%m/%Y") %></p>     
      <label class="flight-card-label">Date</label>
    </div>
    <div class="flight-card-detail"> 
      <p><%= @flight.date.strftime("%H:%M - ")%><%=endTime(@flight)%></p>     
      <label class="flight-card-label">Flight Time</label>
    </div>
    <div class="flight-card-detail">  
      <p><%= @flight.airline %></p>    
      <label class="flight-card-label">Airline</label>
    </div>
    <div class="flight-card-detail"> 
      <% if @flight.layovers === 0 %>
        <p>Non-Stop</p>
      <%elsif @flight.layovers === 1%>    
        <p><%= @flight.layovers%> Stop</p> 
      <%else%>
        <p><%= @flight.layovers%> Stops</p> 
      <%end%>     
      <label class="flight-card-label">Layovers</label>
    </div>
    <div class="flight-card-detail">  
      <p><%= @flight.duration %> Hours</p>    
      <label class="flight-card-label">Duration</label>
    </div>
    <div class="flight-card-detail">  
      <p>$<%= @totalPrice %></p>    
      <label class="flight-card-label">Price</label>
    </div>
  </main>
</div>

app/views/bookings/_passenger.html.erb
<%= form_for @booking, html: {id: "passenger-forms", class: "mt-3"} do |f| %>
  <% passenger_count = 1 %>
  <%= f.fields_for :passengers do |p| %>
    <div class="passenger-form">
      <div class="passenger-container">
        <header class="passenger-header">
          <h6>Passenger # <%=passenger_count%></h6>
        </header>
        <main class="passenger-main">
          <div class="form-group mb-3">
            <label for="name">Name</label>
            <%= p.text_field :name, class: "form-control", required: "required" %>
          </div>
          <div class="form-group mb-3">
            <label for="email">Email</label>
            <%= p.text_field :email, class: "form-control", required: "required", type: "email" %>
          </div>
        </main>
      </div>
    </div>
    <%passenger_count += 1%>    
  <% end %>
  <%= f.hidden_field(:flight_id, value: @flight.id) %>
  <%= f.submit class: "btn btn-primary btn-block passenger-button" %>
<% end %>

app/views/bookings/new.html.erb
<div class="container mt-5">
  <input
      class="btn btn-outline-secondary"
      action="action"
      onclick="window.history.go(-1); return false;"
      type="submit"
      value="<< Go Back"
  />
  <h2 class="mt-3">Flight Overview</h2>
  <p class="mt-3">Departing from: <%= @flight.from_airport.name %></p>
  <p class="mb-3">Arriving in: <%= @flight.to_airport.name %></p>
  <%= render 'bookings/flight'%>
  <h2 class="mt-5">Passenger Details</h2>
  <h6>Please fill out the following fields for each passenger to ensure faster boarding times.</h6>
  <%= render 'bookings/passenger'%>
</div>

app/views/bookings/show.html.erb
<div class="container mt-5">
  <h2>Thanks For Booking With Us!</h2>
  <h3 class="mt-3">Flight Details</h3>
  <%= render 'bookings/flight'%>
  <h3 class="mt-5">Passenger Details</h3>
  <div id="passenger-container">
    <% @passengers.each_with_index do |p, i| %>
      <div class="passenger-details">
        <header class="passenger-header">  
          <h6>Passenger #<%= i+1 %></h6>
        </header>
        <main class="passenger-main">
          <div class="passenger-detail">
            <label>Passenger Name</label>
            <h6 class="card-title"><%= p.name %></h6>
          </div>
          <div class="passenger-detail">
            <label>Passenger Email</label>
            <h6 class="card-title"><%= p.email %></h6>
          </div>
        </main>
      </div>
    <%end%>
  </div>
</div>

app/views/flights/_flight.html.erb
<%= form_with url: new_booking_path, method: :get, local: true do |f| %>
<%= hidden_field_tag(:passengers, params["passengers"]) %>
<%= hidden_field_tag(:flight_id, flight.id) %>
  <header class="flight-header">
  <h6 class="header-date"><%=flight.date.strftime("%B %dst, %Y") %></h6>
  </header>
  <div class="flight-container">
    <div class="flight-card-details">
      <div class="flight-card-detail">
        <p><%= flight.date.strftime("%H:%M") %> - <%= endTime(flight) %></p>
        <label class="flight-card-label"><%= flight.airline %></label>
      </div>
      <div class="flight-card-detail"> 
        <% if flight.layovers === 0 %>
          <p>Non-Stop</p>
        <%elsif flight.layovers === 1%>    
          <p><%= flight.layovers%> Stop</p> 
        <%else%>
          <p><%= flight.layovers%> Stops</p> 
        <%end%>    
      </div>
      <div class="flight-card-detail">     
        <p><%= flight.duration %> Hours</p> 
        <label class="flight-card-label"><%= @flights[0].from_airport.airport_code %><i class="fas fa-arrow-right ml-1 mr-1"></i><%= @flights[0].to_airport.airport_code %></label>
      </div>
      <div class="flight-card-detail">     
        <p>$<%= priceAdjuster(flight, params) %></p> 
      </div>
      <%= f.submit "Select", class: "btn btn-primary flight-card-button" %>
    </div>
  </div>
<%end%>

app/views/flights/_flight_index_header.html.erb
<header id="flight-index-header">
  <div id="flight-index-header-left">
    <h2>Found <%=@totalFlights.length%> Flights</h2>
    <p><%=@flights[0].from_airport.name %> to <%= @flights[0].to_airport.name %></p>
  </div>
  <form method="get" url='search/'> 
    <input type="hidden" name="from" value="<%=@params[:from]%>" />
    <input type="hidden" name="to" value="<%=@params[:to]%>"/>
    <input type="hidden" name="passengers" value="<%=@params[:passengers]%>" />
    <select name="option" class="custom-select" onChange={this.form.submit()}>
      <% if @params[:option] === "price" %>
        <option value="date">Earliest First</option>
        <option value="price" selected="selected">Cheapest First</option>
        <option value="duration">Quickest First</option>
      <% elsif @params[:option] === "duration" %>
        <option value="date">Earliest First</option>
        <option value="price">Cheapest First</option>
        <option value="duration" selected="selected">Quickest First</option>
      <% else %>
        <option value="date" selected="selected">Earliest First</option>
        <option value="price">Cheapest First</option>
        <option value="duration">Quickest First</option>
      <%end%>
    </select>
  </form>
</header>
  

app/views/flights/home.html.erb
<div id="search-container">
  <div class="container"> 
    <%= form_with url: 'search/', method: :get, local: true, id: "main-form" do |f| %>
      <h3 class="form-heading">Find Flights</h3> 
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <div class="form-group mt-3">
        <%= f.label "Departing From" %>
        <%= f.select(:from, options_for_select(@airports, params[:from]), {},
        {class: "form-control"})%>
      </div>

      <div class="form-group mt-3">
        <%= f.label "Arriving In" %>
        <%= f.select(:to, options_for_select(@airports, params[:to]), {}, {class: "form-control"}) %>
      </div>

      <div class="form-group mt-3">
        <%= f.label "Passengers" %>
        <%= f.select(:passengers, options_for_select(1..4, 
        params[:passengers]), {}, {class: "form-control"}) %>
      </div>

      <div class="form-group">
        <%= f.submit(value: "Search", class: "btn btn-primary btn-block mt-3")%>
      </div>
    <%end%>
    <%= render "/partials/footer"%>
  </div> 
</div>

app/views/flights/search.html.erb
<div id="results-container" class="mt-3">
  <%= render "flight_index_header"%>
  <div id="flight-index">
    <%= render @flights %>
  </div>
  <div class="pagination-container">
    <%= will_paginate %>
  </div>
</div>

app/views/layouts/_defaults.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta charset="UTF-8">
<meta name="description" content="Ruby on Rails web application using a sequenced form">
<meta name="author" content="Kgilla">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta property="og:title" content="Fly Away" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://fly-book.herokuapp.com/" />
<meta
  property="og:image"
  content="https://fly-book.herokuapp.com/screenshots/Screen Shot 2020-10-26 at 12.58.31 PM.png"
/>
<%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/png' %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<script src="https://kit.fontawesome.com/643e5a8a38.js" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fly Away</title>
    <%= render 'layouts/defaults' %>
  </head>
  <body>
    <%= render "/partials/header"%>
    <div id="main">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer id="main-footer">
  <a href="https://github.com/kgilla" target="_blank" class="icon-link"><i class="fab fa-github"></i></a>
</footer>

app/views/partials/_header.html.erb
<header id="main-header">
    <%= link_to "Fly Away", root_path, class: "heading"%>
    <i class="fas fa-plane-departure" id="plane"></i>
</header>